### PR TITLE
fix(change-password): fixed bug that made change password not work

### LINKED ISSUE #55: [bug] change password is not working
Whenever you change the password Firebase returns "invalid token" since it expires due to a major user info change. So the error means sucess. If the error is different than that so an error message should be displayed.

### PR DESCRIPTION
**Pull request by murosfc**
closes #55

### CODE REVIEW

File: src/app/authentication/change-password-page/change-password-page.component.ts [hunk 1]
```diff
@@ -89,6 +99,36 @@ export class ChangePasswordPageComponent implements OnDestroy {
...
+          ? this.minLetterValidator.set(inputError.sucess)
+          : this.minLetterValidator.set(inputError.error);
+        this.passwordTest(password)['minNumValidator']
+          ? this.minNumValidator.set(inputError.sucess)
+          : this.minNumValidator.set(inputError.error);
+        this.passwordTest(password)['minTotalCharValidator']
+          ? this.minTotalCharValidator.set(inputError.sucess)
+          : this.minTotalCharValidator.set(inputError.error);
+      }
+    });
```
Comment (rosostolato) [inline src/app/authentication/change-password-page/change-password-page.component.ts:120]: Create form validators instead

**Review by rosostolato — CHANGES_REQUESTED** [review]

**Comment by murosfc** [comment]
form validators is there since always. 
Removed live UI validators in order to close the issue and fix the bug.
The UI thing can be done other time.

**Review by rosostolato — APPROVED** [review]
Lgtm
